name = "seo-worker"
compatibility_date = "2026-06-05"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SEO_KV"
id = "7ba402e0e8964469890aa19bd75f938f"

[triggers]
crons = ["0 9 * * *"]
